# This is a simple powershell command execution task for Dev Box.
$schema: "1.0"
name: mypowershell
description: Execute a powershell command.
author: Microsoft Corporation
command: ".\\Run-Command.ps1 -Command {{command}} -WorkingDirectory {{workingDirectory}} -RunAsUser {{runAsUser}}"
parameters:
  command:
    type: string
    default: ""
    required: true
    description: The command to execute.
  workingDirectory:
    type: string
    default: ""
    required: false
    description: The working directory to execute the command in.
  runAsUser:
    type: boolean
    default: false
    required: false
    description: execute the command when the user login the devbox at the first time.
documentation:
  notes: This task is used to execute a powershell command.
  examples:
    - name: printhello
      description: print hello world
      parameters:
        command: "Write-Host 'hello, world!'"
    - name: run-script
      description: run script
      parameters:
        command: "./script.ps1"
        workingDirectory: C:\\provisioning\\temp
