name: Sandbox
on:
  workflow_dispatch:
  
jobs:
  get_current_step:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: echo Hello World
